# SITE CONFIGURATION
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "/blog/_layouts/about.md" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Raza Habib
  author: Raza Habib
  avatar: photo.jpg
  gravatar:
  description:

  header_text:
  header_text_feature_image:
  footer_text: >
    © 2016 ・ <a class="plain" href="https://github.com/Razcle">Raza</a>

  # Icons
  rss: false
  email_address:
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "razcle"
  google_plus:
  instagram:
  linkedin:
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube:

  # Scripts
  google_analytics:
  disqus_shortname:
  katex: true

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# BUILD SETTINGS
permalink: "/:title"
sass:
  sass_dir: _sass
  style: :compressed
